#Deployment of the batch job
steps:
  # Build the Docker image for the batch job
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/model-train-batch-image:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/model-train-batch-image:latest', './src']
    # Push the Docker image with the specific SHA tag to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/model-train-batch-image:$SHORT_SHA']
  # Push the Docker image with the latest tag to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/model-train-batch-image:latest']