# Use a slim Python base image for optimization
FROM python:3.9-slim-buster

# Set the working directory within the container
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Python script and any other necessary files
COPY configuration_schemas.py .
COPY build_ffn_configured.py . 
COPY load_features.py . 
COPY main.py . 
# Add any additional files or directories as needed

# Set environment variables (replace with your actual values)
# ENV GOOGLE_APPLICATION_CREDENTIALS="/app/your-service-account-key.json" 
# ENV OTHER_VARIABLE="value"

# Specify the command to run when the container starts
CMD ["python", "main.py"]